workflows:
  flutter-apk-from-zip:
    name: Flutter APK from ZIP
    max_build_duration: 60
    environment:
      flutter: stable  # default channel; kita atur spesifik di skrip juga jika perlu
      xcode: 15.0  # diabaikan untuk Android
      java: 17
      vars:
        ZIP_NAME: app.zip
        FLUTTER_VERSION: "3.24.0"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      # --- Setup Flutter version yang pasti ---
      - name: Ensure Flutter $FLUTTER_VERSION
        script: |
          fvm flutter --version >/dev/null 2>&1 || true
          # Codemagic sudah include Flutter; kita pastikan versinya cocok
          flutter --version
          # (Optional) ganti versi:
          # flutter version $FLUTTER_VERSION || true

      - name: Find & unzip project ZIP
        script: |
          set -e
          cd "$CM_BUILD_DIR"
          if [ -f "$ZIP_NAME" ]; then
            ZIP="$ZIP_NAME"
          else
            ZIP=$(ls -1 *.zip | head -n 1 || true)
          fi
          if [ -z "$ZIP" ]; then
            echo "No ZIP found in repo root. Upload $ZIP_NAME." >&2
            exit 1
          fi
          echo "Using ZIP: $ZIP"
          unzip -q "$ZIP" -d extracted

          # Resolve PUBROOT (folder yang ada pubspec.yaml)
          if [ -f "extracted/pubspec.yaml" ]; then
            PUBROOT="extracted"
          else
            found=$(find extracted -maxdepth 3 -name pubspec.yaml | head -n 1 || true)
            if [ -z "$found" ]; then
              echo "pubspec.yaml not found inside zip." >&2
              exit 1
            fi
            PUBROOT="$(dirname "$found")"
          fi
          echo "PUBROOT=$PUBROOT" >> $CM_ENV
          echo "Resolved PUBROOT=$PUBROOT"

      - name: Auto-create Android platform if missing
        script: |
          set -e
          cd "$PUBROOT"
          if [ ! -f android/build.gradle ]; then
            echo "Android folder missing -> flutter create ."
            flutter create .
          fi

      - name: Patch Kotlin/Gradle for Flutter 3.24.x
        script: |
          set -e
          cd "$PUBROOT"
          # Patch kotlin version & AGP in android/build.gradle (root)
          if [ -f android/build.gradle ]; then
            if grep -q 'ext.kotlin_version' android/build.gradle; then
              sed -i 's/ext.kotlin_version *= *".*"/ext.kotlin_version = "1.9.24"/' android/build.gradle || true
            fi
            if grep -q 'com.android.tools.build:gradle' android/build.gradle; then
              sed -i 's/com\.android\.tools\.build:gradle:[^"]*/com.android.tools.build:gradle:8.5.2/' android/build.gradle || true
            fi
          fi
          # gradle wrapper -> 8.5
          if [ -f android/gradle/wrapper/gradle-wrapper.properties ]; then
            sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.5-bin.zip#' android/gradle/wrapper/gradle-wrapper.properties
          fi
          # jvmargs aman
          echo 'org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8' >> android/gradle.properties

      - name: Flutter pub get
        script: |
          cd "$PUBROOT"
          flutter pub get

      - name: Build APK (release)
        script: |
          set -e
          cd "$PUBROOT"
          flutter build apk --release
          # Salin ke path artifacts yang statis
          cp build/app/outputs/flutter-apk/app-release.apk "$CM_BUILD_DIR/app-release.apk"

    artifacts:
      - $CM_BUILD_DIR/app-release.apk
