name: Build Flutter from ZIP (auto-create Android)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find project ZIP
        id: findzip
        run: |
          set -e
          if [ -f "app.zip" ]; then
            echo "zipfile=app.zip" >> $GITHUB_OUTPUT
          else
            first_zip=$(ls -1 *.zip | head -n 1 || true)
            if [ -z "$first_zip" ]; then
              echo "No ZIP found in repo root. Please upload your Flutter project ZIP (e.g., app.zip)." >&2
              exit 1
            fi
            echo "zipfile=$first_zip" >> $GITHUB_OUTPUT
          fi

      - name: Unzip project
        run: |
          set -e
          unzip -q "${{ steps.findzip.outputs.zipfile }}" -d extracted
          topdir=$(ls -1 extracted | head -n 1)
          if [ -f "extracted/pubspec.yaml" ]; then
            echo "PUBROOT=extracted" >> $GITHUB_ENV
          elif [ -d "extracted/$topdir" ] && [ -f "extracted/$topdir/pubspec.yaml" ]; then
            echo "PUBROOT=extracted/$topdir" >> $GITHUB_ENV
          else
            found=$(find extracted -maxdepth 3 -name pubspec.yaml | head -n 1 || true)
            if [ -z "$found" ]; then
              echo "pubspec.yaml not found inside zip. Ensure your zip contains a Flutter project." >&2
              exit 1
            fi
            echo "PUBROOT=$(dirname "$found")" >> $GITHUB_ENV
          fi
          echo "Resolved PUBROOT=$PUBROOT"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Ensure platforms exist (auto flutter create)
        working-directory: ${{ env.PUBROOT }}
        run: |
          set -e
          if [ ! -d "android" ] || [ ! -f "android/build.gradle" ]; then
            echo "Android folder not found. Running 'flutter create .' to scaffold platforms..."
            flutter create .
          fi

      - name: Flutter pub get
        working-directory: ${{ env.PUBROOT }}
        run: flutter pub get

      - name: Build APK (release)
        working-directory: ${{ env.PUBROOT }}
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            ${{ env.PUBROOT }}/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
